# Generated by Django 4.1.3 on 2023-01-11 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kot",
            name="items",
            field=models.JSONField(default=list),
        ),
    ]
