# Generated by Django 4.1.3 on 2023-01-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_alter_kot_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="kot",
            old_name="bill",
            new_name="invoice",
        ),
        migrations.AddField(
            model_name="invoice",
            name="amount_paid",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="order",
            name="size",
            field=models.CharField(
                choices=[("Half", "Half"), ("Full", "Full")],
                default="Full",
                max_length=16,
            ),
        ),
    ]
