# Generated by Django 4.1.3 on 2023-01-13 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_staff"),
        ("finance", "0004_rename_bill_kot_invoice_invoice_amount_paid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="kitchen.staff",
            ),
        ),
    ]
