# Generated by Django 4.1.3 on 2023-02-28 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_remove_kot_items_order_kot_alter_order_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kot",
            name="invoice",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="finance.invoice"
            ),
        ),
    ]
