# Generated by Django 4.1.3 on 2023-03-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_alter_kot_invoice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
