# Generated by Django 4.1.3 on 2023-03-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_alter_invoice_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="invoice_number_full",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
