# Generated by Django 4.1.3 on 2023-03-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0009_invoice_invoice_number_full"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="dish_description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
