# Generated by Django 4.1.3 on 2023-04-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_order_dish_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="invoice",
            name="delivery_charge",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="invoice",
            name="net_amount",
            field=models.FloatField(default=0.0),
        ),
    ]
