# Generated by Django 4.1.3 on 2022-12-07 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=256, unique=True)),
                ("gstin", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "fssai_number",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "address_street",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "address_city",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "address_state",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "address_country",
                    models.CharField(
                        blank=True,
                        choices=[("India", "India")],
                        default="India",
                        max_length=256,
                        null=True,
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                ("contact", models.CharField(blank=True, max_length=32, null=True)),
                (
                    "display_name",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="authentication.restaurant",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "restaurant")},
            },
        ),
    ]
