# Generated by Django 4.1.3 on 2023-01-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="upi_id",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
