# Generated by Django 4.1.3 on 2023-03-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_restaurant_upi_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="invoice_prefix",
            field=models.CharField(default="", max_length=16),
        ),
    ]
