# Generated by Django 4.1.3 on 2023-01-11 19:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_restaurant_upi_id"),
        ("kitchen", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=64)),
                ("contact", models.CharField(blank=True, max_length=16, null=True)),
                ("address", models.CharField(blank=True, max_length=256, null=True)),
                ("date_of_joining", models.DateField(blank=True, null=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="authentication.restaurant",
                    ),
                ),
            ],
            options={
                "unique_together": {("name", "restaurant")},
            },
        ),
    ]
