# Generated by Django 4.1.3 on 2023-01-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_staff"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="dish_type",
            field=models.CharField(
                choices=[("Veg", "Veg"), ("Non-Veg", "Non Veg")],
                default="Veg",
                max_length=64,
            ),
        ),
    ]
