# Generated by Django 4.1.3 on 2023-03-16 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_restaurant_invoice_prefix"),
        ("kitchen", "0003_dish_dish_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dish",
            unique_together={("restaurant", "name", "category", "is_deleted")},
        ),
    ]
