# Generated by Django 4.1.3 on 2023-03-16 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0004_alter_dish_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dish",
            unique_together=set(),
        ),
    ]
