# Generated by Django 4.1.3 on 2023-03-22 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_restaurant_invoice_prefix"),
        ("kitchen", "0005_alter_dish_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dish",
            unique_together={("restaurant", "name", "category")},
        ),
    ]
