# Generated by Django 4.1.3 on 2023-04-02 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0006_alter_dish_unique_together"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dish",
            index=models.Index(
                fields=["restaurant", "is_deleted"],
                name="kitchen_dis_restaur_b2175b_idx",
            ),
        ),
    ]
