# Generated by Django 4.1.3 on 2023-04-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0007_dish_kitchen_dis_restaur_b2175b_idx"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="dishrate",
            index=models.Index(
                fields=["dish", "is_deleted"], name="kitchen_dis_dish_id_7f63d4_idx"
            ),
        ),
    ]
